name: chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2

  #firbase
  firebase_core:
  firebase_auth:
  google_sign_in:
  firebase_storage:
  cloud_firestore:

  #features management
  connectivity_plus:
  uuid: ^3.0.4
  image_picker:
  provider:
  permission_handler:
  agora_rtc_engine:

  #ui
  flutter_spinkit:
  bottom_navy_bar:
  lottie:






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/lottie/
    - assets/images/


  fonts:
   - family: IndieFlower
     fonts:
      - asset: assets/fonts/IndieFlower-Regular.ttf

